const HTTP_SUCCESS_OK = 200;
const HTTP_BAD_REQUEST_ERROR = 400;
const HTTP_AUTHORIZATION_ERROR = 401;
const HTTP_FORBIDDEN_ERROR = 403;
const HTTP_NOT_FOUND_ERROR = 404;
const HTTP_CONFLICT_ERROR = 409;
const HTTP_INTERNAL_SERVER_ERROR = 500;

module.exports = {
  HTTP_SUCCESS_OK,
  HTTP_BAD_REQUEST_ERROR,
  HTTP_AUTHORIZATION_ERROR,
  HTTP_FORBIDDEN_ERROR,
  HTTP_NOT_FOUND_ERROR,
  HTTP_CONFLICT_ERROR,
  HTTP_INTERNAL_SERVER_ERROR,
};
